<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>tex.erb</string>
  </array>
  <key>foldingStartMarker</key>
  <string>/\*\*|\{\s*$</string>
  <key>foldingStopMarker</key>
  <string>\*\*/|^\s*\}</string>
  <key>name</key>
  <string>TeX ERB</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>begin</key>
      <string>&lt;%+(?!&gt;)[-=]?</string>
      <key>captures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.tex.erb</string>
        </dict>
      </dict>
      <key>end</key>
      <string>-?%&gt;</string>
      <key>name</key>
      <string>source.tex.erb</string>
      <key>patterns</key>
      <array>
        <!-- capture headings -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>heading_method.tex.erb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>heading_arguments.tex.erb</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<%= )(h\d)\b(.+?)(?=\ %>)]]></string>
        </dict>

        <!-- capture footnotes -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>footnote_method.tex.erb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>footnote_arguments.tex.erb</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<%= )(fq?\b)(.+?)(?=\ %>)]]></string>
        </dict>

        <!-- capture method calls that should be readable inline  -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>inline_method.tex.erb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>inline_first_argument.tex.erb</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>inline_arguments.tex.erb</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<%= )(abk|b|i|erst_nennung)\b(.+?)(,.+?)?(?=\ %>)]]></string>
        </dict>

        <!-- capture method calls that result in a "block" in the PDF -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>block_method.tex.erb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>block_first_argument.tex.erb</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>block_arguments.tex.erb</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<%= )(label|figure|input|render)\b(.+?)(,.+?)?(?=\ %>)]]></string>
        </dict>

        <!-- capture references -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>reference_method.tex.erb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>reference_arguments.tex.erb</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<%= )(abbildung|autor|kapitel|quote)\b(.+?)(?=\ %>)]]></string>
        </dict>


        <!-- capture all other ERb method calls -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>helper_method.tex.erb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>helper_arguments.tex.erb</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<%= )([a-zA-Z0-9_\?\!\*]+)\b(.+?)(?=\ %>)]]></string>
        </dict>

        <!-- capture erb blocks -->
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.tex.erb.block_method</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>source.tex.erb.block_arguments</string>
            </dict>
          </dict>
          <key>match</key>
          <string><![CDATA[(?<=\<% )([a-zA-Z0-9_\?\!\*]+)\b(.+?)?(?=\ %>)]]></string>
        </dict>
      </array>
    </dict>



    <dict>
      <key>include</key>
      <string>text.tex.latex</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>text.tex.erb</string>
  <key>uuid</key>
  <string>6BC8DE6F-9360-4C7E-AC3C-971385945346</string>
</dict>
</plist>